### ISSUE TITLE
No permission on guild after kick

### ISSUE THREAD

**Issue by rexlNico** [cerus/jda-slash-commands#13]
After i kicked a bot from my guild and then reinvited it I cant add commands to the guild any more.
On every other guild the commands will get added.
`java.util.concurrent.CompletionException: dev.cerus.jdasc.http.DiscordApiException: Expected one of [200] but got 403
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at dev.cerus.jdasc.http.DiscordHttpClient.lambda$execute$1(DiscordHttpClient.java:222)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: dev.cerus.jdasc.http.DiscordApiException: Expected one of [200] but got 403
	... 6 more`

**Comment by cerus** [comment]
Did you invite the bot with the correct permissions?

**Comment by rexlNico** [comment]
Yes, I tried it with admin permission only and after that i gave the bot every permission but it still does not work.

**Comment by cerus** [comment]
Did you create the invite link with the slash commands scope? ([Image](https://user-images.githubusercontent.com/80323633/116818363-3ee55780-ab6b-11eb-99fe-6123fb1c64d6.png))

**Comment by rexlNico** [comment]
Ohh i totaly forgot about that, i tried it and it worked.
Thanks for the help.
