### ISSUE TITLE
initCommands crashes the example.

### ISSUE THREAD

**Issue by VingGit** [cerus/jda-slash-commands#3]
like so:

`Caused by: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at de.cerus.jdasc.http.DiscordHttpClient.submitGlobalCommand(DiscordHttpClient.java:127)
	at de.cerus.jdasc.JDASlashCommands.submitGlobalCommand(JDASlashCommands.java:159)
	at Botti.Botti.initCommands(Botti.java:54)
	at Botti.Botti.launchBot(Botti.java:42)
	at GUI.ControllerForLogin.login(ControllerForLogin.java:41)
	... 62 more`
	
and when you comment it out, it works just fine.

here's the repo with the most up to date branch: https://github.com/VingGit/UnicaBot/tree/gui-jatkokehitys

i'm unsure whether the problem is on my end or yours,(prolly mine tho) but i seem to have struck a wall once more.

**Comment by VingGit** [comment]
` <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.1</version>
        </dependency>`

nvm, just updated the pom

**Comment by VingGit** [comment]
and now it works like a charm!

ps: i suggest you include that in your maven setup
